import type { GroceryCategory } from "@/generated/prisma/enums";

type Rule = { category: GroceryCategory; keywords: string[] };

/**
 * Rules are checked top to bottom and the first match wins, so specific
 * phrases ("ice cream", "chicken stock") sit above the general words they
 * contain ("cream", "chicken").
 */
const RULES: Rule[] = [
  {
    category: "FROZEN",
    keywords: [
      "frozen",
      "ice cream",
      "gelato",
      "sorbet",
      "popsicle",
      "ice cube",
      "pizza",
      "fish finger",
      "fish stick",
      "waffle",
      "tater tot",
      "hash brown",
    ],
  },
  {
    category: "PANTRY",
    keywords: [
      "black pepper",
      "white pepper",
      "ground pepper",
      "peppercorn",
      "peanut butter",
      "almond butter",
      "cocoa butter",
      "coconut milk",
      "coconut cream",
      "condensed milk",
      "evaporated milk",
      "chicken stock",
      "chicken broth",
      "beef stock",
      "beef broth",
      "vegetable stock",
      "vegetable broth",
      "stock cube",
      "tomato sauce",
      "tomato paste",
      "canned tomato",
      "tinned tomato",
      "soy sauce",
      "hot sauce",
      "bbq sauce",
      "olive oil",
      "vegetable oil",
      "cooking oil",
      "sesame oil",
      "baking soda",
      "baking powder",
      "corn starch",
      "cornstarch",
    ],
  },
  {
    category: "HOUSEHOLD",
    keywords: [
      "toilet paper",
      "paper towel",
      "kitchen roll",
      "dish soap",
      "washing up liquid",
      "dishwasher",
      "laundry",
      "detergent",
      "fabric softener",
      "bleach",
      "sponge",
      "trash bag",
      "bin bag",
      "garbage bag",
      "cling film",
      "plastic wrap",
      "aluminum foil",
      "aluminium foil",
      "tin foil",
      "baking paper",
      "parchment",
      "napkin",
      "tissue",
      "soap",
      "shampoo",
      "conditioner",
      "toothpaste",
      "toothbrush",
      "deodorant",
      "razor",
      "cleaner",
      "cleaning",
      "disinfectant",
      "light bulb",
      "battery",
      "batteries",
      "candle",
      "matches",
      "diaper",
      "nappy",
      "nappies",
      "wipes",
      "sanitizer",
      "sanitiser",
    ],
  },
  {
    category: "DAIRY",
    keywords: [
      "milk",
      "cheese",
      "cheddar",
      "mozzarella",
      "parmesan",
      "feta",
      "brie",
      "halloumi",
      "ricotta",
      "cream cheese",
      "cottage cheese",
      "yogurt",
      "yoghurt",
      "butter",
      "margarine",
      "cream",
      "sour cream",
      "half and half",
      "creamer",
      "egg",
      "kefir",
      "custard",
    ],
  },
  {
    category: "MEAT",
    keywords: [
      "chicken",
      "turkey",
      "duck",
      "beef",
      "steak",
      "mince",
      "ground beef",
      "ground turkey",
      "pork",
      "bacon",
      "ham",
      "sausage",
      "salami",
      "prosciutto",
      "chorizo",
      "hot dog",
      "lamb",
      "veal",
      "ribs",
      "brisket",
      "meatball",
      "salmon",
      "tuna",
      "cod",
      "haddock",
      "tilapia",
      "trout",
      "sardine",
      "anchovy",
      "shrimp",
      "prawn",
      "crab",
      "lobster",
      "mussel",
      "scallop",
      "fish",
      "seafood",
    ],
  },
  {
    category: "PRODUCE",
    keywords: [
      "apple",
      "banana",
      "orange",
      "lemon",
      "lime",
      "grapefruit",
      "grape",
      "strawberry",
      "blueberry",
      "raspberry",
      "blackberry",
      "berry",
      "cherry",
      "peach",
      "nectarine",
      "plum",
      "pear",
      "mango",
      "pineapple",
      "watermelon",
      "melon",
      "kiwi",
      "avocado",
      "pomegranate",
      "fig",
      "tomato",
      "potato",
      "sweet potato",
      "onion",
      "shallot",
      "scallion",
      "spring onion",
      "leek",
      "garlic",
      "ginger",
      "carrot",
      "celery",
      "cucumber",
      "zucchini",
      "courgette",
      "eggplant",
      "aubergine",
      "pepper",
      "bell pepper",
      "chili",
      "chilli",
      "jalapeno",
      "broccoli",
      "cauliflower",
      "cabbage",
      "kale",
      "spinach",
      "lettuce",
      "salad",
      "rocket",
      "arugula",
      "mushroom",
      "corn on the cob",
      "sweetcorn",
      "asparagus",
      "beetroot",
      "beet",
      "radish",
      "squash",
      "pumpkin",
      "pea",
      "green bean",
      "herb",
      "basil",
      "parsley",
      "cilantro",
      "coriander",
      "mint",
      "dill",
      "rosemary",
      "thyme",
      "fruit",
      "veg",
      "vegetable",
    ],
  },
  {
    category: "PANTRY",
    keywords: [
      "flour",
      "sugar",
      "salt",
      "spice",
      "cumin",
      "paprika",
      "cinnamon",
      "oregano",
      "vanilla",
      "yeast",
      "rice",
      "pasta",
      "spaghetti",
      "penne",
      "macaroni",
      "noodle",
      "couscous",
      "quinoa",
      "oats",
      "oatmeal",
      "cereal",
      "granola",
      "muesli",
      "bread",
      "bagel",
      "tortilla",
      "wrap",
      "bun",
      "roll",
      "cracker",
      "biscuit",
      "cookie",
      "chip",
      "crisps",
      "popcorn",
      "pretzel",
      "nut",
      "almond",
      "walnut",
      "cashew",
      "pistachio",
      "peanut",
      "seed",
      "raisin",
      "dried fruit",
      "honey",
      "syrup",
      "jam",
      "jelly",
      "marmalade",
      "nutella",
      "chocolate",
      "candy",
      "sweets",
      "oil",
      "vinegar",
      "ketchup",
      "mustard",
      "mayo",
      "mayonnaise",
      "sauce",
      "dressing",
      "salsa",
      "pesto",
      "hummus",
      "stock",
      "broth",
      "soup",
      "bean",
      "lentil",
      "chickpea",
      "canned",
      "tinned",
      "tin",
      "can",
      "coffee",
      "tea",
      "juice",
      "soda",
      "cola",
      "water",
      "sparkling",
      "squash cordial",
      "cordial",
      "wine",
      "beer",
      "tofu",
    ],
  },
];

function escapeRegex(s: string) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// Whole-word match that tolerates simple plurals ("egg" matches "eggs",
// "tomato" matches "tomatoes", "berry" matches "berries").
function keywordRegex(keyword: string) {
  const stem = keyword.endsWith("y")
    ? `(?:${escapeRegex(keyword.slice(0, -1))}y|${escapeRegex(keyword.slice(0, -1))}ies)`
    : `${escapeRegex(keyword)}(?:s|es)?`;
  return new RegExp(`(?:^|[^a-z])${stem}(?![a-z])`);
}

const COMPILED = RULES.map((rule) => ({
  category: rule.category,
  patterns: rule.keywords.map(keywordRegex),
}));

/** Guess a grocery category from an item name. Falls back to OTHER. */
export function categorize(name: string): GroceryCategory {
  const text = name
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "") // "jalapeño" -> "jalapeno"
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
  if (!text) return "OTHER";

  for (const { category, patterns } of COMPILED) {
    if (patterns.some((p) => p.test(text))) return category;
  }
  return "OTHER";
}
